### PR TITLE
Add MQTT port and OTA path & port to config

### LINKED ISSUE #3: Add config for MQTT port
To use it with a std MQTT broker it could be nice to make MQTT broker port configurable.

It's straightforward to add such option, however in a "pure" Homie framework it's just an other useless option... 

What do you think to add an `homie_port` option that take the value from the `HOMIE_PORT` constant if not given in the config JSON ?

I can propose a PR in this sense.

### PR DESCRIPTION
**Pull request by enavarro222**
This should close #3, this also include #6 but with to call to the log mth : 
* when config is saved in config mode
* at setup time in normal mode

### CODE REVIEW

**Comment by marvinroger** [comment]
Sorry for the delay. Great! I only have a single objection: I don't like the fact the Wi-Fi password is exposed. Do you mind removing this sensitive information from the log method?

**Comment by enavarro222** [comment]
Ok, I'll change that

**Comment by enavarro222** [comment]
Done.

I just remove the password log for now.
Latter, t might be useful to indicate if there is a stored password or not...

**Comment by marvinroger** [comment]
Awesome. Thanks!

**Pull request merged**
