### PR TITLE
Use new name of Json library

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by marvinroger** [comment]
It was indeed pretty confusing, thanks.

**Comment by ivankravets** [comment]
What do you mean under confusing? The previous name?

**Comment by marvinroger** [comment]
Yes, well in other words it's a good thing it's now published under `ArduinoJson`.

**Comment by ivankravets** [comment]
Aaa :) Cool. I don't remember why we named this library with `Json` previously.

**Pull request merged**
