### PR TITLE
Add graceful MQTT disconnect

### PR DESCRIPTION
**Pull request by clough42**
This request adds a new method to HomieClass:  disconnect().

This is plumbed through to the NormalConfig class, where it:

- Sends the $online: false message
- Waits for the $online: false (and any messages before it) to be delivered to the broker
- Disconnects MQTT
- Triggers HomieEvent::DISCONNECTED after the broker shuts down
- Prevents MQTT or WiFi from attempting to reconnect if the shutdown was requested using the disconnect() method

There has been some discussion in #138 as to whether this should be in Homie.  I'm submitting it here for discussion.  Feel free to reject it or ask for changes.

One option I'm considering:  Rename the method from disconnect() to prepareForSleep().  This probably makes more sense and makes all of the internal names clearer.  Then it could trigger HomieEvent::PREPARED_FOR_SLEEP or something like that.

Like I said, feel free to reject or discuss.

### CODE REVIEW

**Comment by marvinroger** [comment]
Yes, `prepareForSleep()` makes more sense, let's change this.
Can you please fix [these stylistic issues](https://travis-ci.org/marvinroger/homie-esp8266/jobs/156300955#L242)? It's not a big deal, but the project is starting to grow and I would like to keep the same conventions.

Other than that, good job! :+1:

**Comment by clough42** [comment]
Yes.  That's no problem.  I'll fix the stylistic issues and change the names.  I won't be able to get to it until later tonight.

**Comment by clough42** [comment]
@marvinroger Pull request updated.  I changed the names:

- disconnect()   to   prepareForSleep()
- _mqttDisconnectRequested   to  _flaggedForSleep
- HomieEvent::DISCONNECTED  to  HomieEvent::READY_FOR_SLEEP

If there's anything else you would like me to change, please let me know.  I'm in your house messing with your code, so I'll be happy to adjust.

**Comment by marvinroger** [comment]
It's all good, thanks a lot @clough42! :smiley:

**Pull request merged**
