### PR TITLE
Change topic check for OTA upload

### PR DESCRIPTION
**Pull request by jesserockz**
Fixes the module crashing as soon as firmware is published into the topic

### CODE REVIEW

**Comment by marvinroger** [comment]
How does adding an `s` to "firmware" fix the crash? A singular `firmware` makes more sense anyway.

**Comment by jesserockz** [comment]
The topic being subscribed to is /firmwares/*
It looks like one was changed but not the other.

https://github.com/marvinroger/homie-esp8266/blob/develop/src/Homie/Boot/BootNormal.cpp#L299

**Comment by marvinroger** [comment]
Oh, right. Would you mind do the opposite, rename both to `firmware` in singular?

**Comment by marvinroger** [comment]
Awesome, thanks a lot!

**Pull request merged**
