### PR TITLE
added OTA status/progress reporting over mqtt

### PR DESCRIPTION
**Pull request by mrpace2**
First cut at enhancement #171

### CODE REVIEW

**Comment by mrpace2** [comment]
Think I'm done with my first cut. Some Mosquitto logs running the latest `homie-ota` master (updated today):

    device/$implementation/ota/payload <firmware blob>
    device/$ota 1.0.0
    device/$implementation/ota/status 202
    device/$implementation/ota/status 206,1405/345520
    device/$implementation/ota/status 206,2865/345520
    device/$implementation/ota/status 206,4325/345520
    ...
    device/$implementation/ota/status 206,343045/345520
    device/$implementation/ota/status 206,344505/345520
    device/$implementation/ota/status 206,345520/345520
    device/$implementation/ota/status 200

Attempt to update to the firmware version currently running:

    device/$implementation/ota/payload <firmware blob>
    device/$ota 1.0.0
    device/$implementation/ota/status 304

Bad firmware blob:

    device/$implementation/ota/payload <patched firmware blob, first byte=FF>
    device/$ota 1.0.0
    device/$implementation/ota/status 202
    device/$implementation/ota/status 206,1405/345520
    device/$implementation/ota/status 206,2865/345520
    ...
    device/$implementation/ota/status 206,344505/345520
    device/$implementation/ota/status 206,345520/345520
    device/$implementation/ota/status 400,OTA failed: ERROR[10]: Magic byte is wrong, not 0xE9

Questions:

- Shall we use a space instead of comma between status code (`206`) and info (`done/total`)? Before Homie, I got very much used to `404 Not Found` :-)

- I am using error messages as provided by `Updater::printError`. Would you prefer simpler error messages with Homie users in mind? For example: `OTA failed (invalid firmware binary)` instead of `OTA failed: ERROR[10]: Magic byte is wrong, not 0xE9`?

**Comment by shogsbro** [comment]
I've been following the discussion, and like the use of HTTP status codes. I also prefer a space instead of a comma as separator between status code and info.

**Comment by marvinroger** [comment]
Yes, let's use spaces!

For the second point, simpler errors would indeed be better for parsing purposes. I would even use some sort of constants (e.g. 400 `BAD_FIRMWARE`), so that an UI could for example show i18n-ed messages.

**Comment by jpmens** [comment]
+1 for the BAD_FIRMWARE codes!

**Comment by flaviostutz** [comment]
Amazing feature! Thanks!

**Comment by marvinroger** [comment]
@mrpace2 when you are done, can you rebase / merge against the `develop` branch? There should be a few conflicts that prevents me from accepting the PR.

**Comment by mrpace2** [comment]
Will do.

**Comment by mrpace2** [comment]
200 OK

(I'm done).

**Comment by marvinroger** [comment]
Awesome 👍 thanks a lot, @mrpace2 !

**Pull request merged**
