### PR TITLE
Simplification on boot modes logic. Now any mode can be triggered programmatically or scheduled for the next boot. + MQTT retry enhancements

### PR DESCRIPTION
**Pull request by flaviostutz**
Same as PR #240

### CODE REVIEW

**Comment by flaviostutz** [comment]
@marvinroger, please check if this is OK now.

**Comment by marvinroger** [comment]
Awesome, thanks! Can you please write the docs?

**Comment by flaviostutz** [comment]
Yes...

**Comment by marvinroger** [comment]
@flaviostutz don't feel obliged! I can do it if you don't want to. You've already done a lot for the project 😉

**Comment by flaviostutz** [comment]
Appreciate your consideration... I was thinking about writing the docs even before you asked... Thanks!

**Pull request merged**
