### PR TITLE
🤔 Add details on how to interact with range property

### PR DESCRIPTION
**Pull request by LiyouZhou**
Add hint to help people figure out how to interact with
range properties. Especially document the `_` separator.

### CODE REVIEW

**Comment by LiyouZhou** [comment]
@marvinroger Could I possibly have a review please?

**Comment by lorenwest** [comment]
haha brilliant minds think alike!

**Comment by lorenwest** [comment]
Deleting pull request #396 as a duplicate. Let's hope there's some love for this PR so others don't waste more time on this issue.

**Comment by marvinroger** [comment]
Hi guys,

Thanks for your PRs, and sorry for the delay; I am currently very busy 😕

**Pull request merged**
