### PR TITLE
#299 Handling millis() overflow in uptime

### PR DESCRIPTION
**Pull request by bertmelis**
Corrected type declaration for correct overflow handling of millis
function in uptime calculation

### CODE REVIEW

**Comment by marvinroger** [comment]
What's the explanation behind the fact that it fixes the issue?

**Comment by marvinroger** [comment]
Oh, maybe because millis returns an `unsigned long` which is, on arduino, 32 bits and not 64?

**Comment by Nzbuu** [comment]
I suspect it's due to the wraparound handling in `(now - _lastTick)`

**Comment by Nzbuu** [comment]
Would it be better to use `unsigned long` rather than `uint32_t` or `uint64_t`?

**Comment by bertmelis** [comment]
millis returnes an unsigned long indeed, which is uint32_t in normal C++.
So the rollover didn't work properly because not everything rolled over (or how should I explain).

Since the rest of the Homie code follows C++ variable declaration uses the standard C++ names, I also used these instead of the Arduino names like "unsigned long". It's better to stick to the general C++ names wrt portability. (as I've read somewhere.)

**Comment by bertmelis** [comment]
If memory is an issue, you could also make the `uint64_t  seconds` and `uint32_t`.
Hence, it would rollover after +130 years, which is quite a while for my little IoT-devices.

**Comment by bertmelis** [comment]
I did a quick scan of the rest of the Homie code. Everywhere else, `uint32_t` variables are used in conjuction with the `millis()` function.

**Comment by marvinroger** [comment]
Yes, good catch! Thanks a lot for your time.

**Comment by bertmelis** [comment]
As @euphi pointed out, the uptime could be not that accurate. Could someone review this solution:

```C++
void Uptime::update() {
  uint32_t now = millis();
  _milliseconds += (now - _lastTick);
  _lastTick = now;
}
uint64_t Uptime::getSeconds() const {
  return _milliseconds / 1000ULL;
}
```

So instead of storing seconds, milliseconds are stored. getSeconds obvoisly still return the uptime in seconds. The cost of this is that the uptime get rolled over earlier. But the max uptime is still 18446744073709551615 milliseconds.

**Pull request merged**
