### PR TITLE
Instruction for @PlatformIO

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by euphi** [comment]
:+1: 

Looks good, however can you add a example for using the latest tagged version (v2.0.0-beta.1)?

@marvinroger BTW: Due to recent progress with the webserver, but also with arduiono platform etc. projects need to be changed to compile. Is it possible to tag the latest version before breaking changes (715ad3f83f2c0667916a3373bd46adc3eedeb88c) with v2.0.0-beta.2 ?

**Comment by ivankravets** [comment]
@euphi Done!

**Comment by ivankravets** [comment]
Also, please merge this https://github.com/marvinroger/homie-esp8266/pull/434 before. Thanks!

**Comment by luebbe** [comment]
yes, a tag would be very helpful. Currently I can neither compile with the develop branch nor with the v2.0.0-beta.1 tag.
Both give different compiler errrors in BootConfig.cpp.

**Comment by marvinroger** [comment]
@euphi the tagging is done!

**Comment by marvinroger** [comment]
Thanks guys. 😉

**Pull request merged**
